### PR TITLE
feat: parallel read

### PR DESCRIPTION
**Pull request by kboroszko**
In this pr we make the read methods accept a row_set reading only rows specified by the user.
We also add a parallel read, that leverages the sample_row_keys method to split work among workers.

---
This change is [Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/4)

### CODE REVIEW

**Review by dopiera — COMMENTED** [review]
This looks good in general, but I am worried that we don't test splitting the work between workers enough.

I'll do the full review after you rebase this.

> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-:-Mng8J4U-V2WszOlNy7c:bksruxj)* status: 0 of 16 files reviewed, all discussions resolved

**Review by kboroszko — COMMENTED** [review]
Good luck! :D
It's rebased!

> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-:-MnlY8Z839HBUBfI5Amj:b7c3o60)* status: 0 of 17 files reviewed, all discussions resolved

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/4)* status: 0 of 18 files reviewed, 8 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 34 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-MtOe724gaO9OO9-e:-Mo-MtOe724gaO9OO9-f:b-233txq) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L34)):*
> ```cpp
> 
> tensorflow::error::Code GoogleCloudErrorCodeToTfErrorCode(
>     ::google::cloud::StatusCode code) {
> ```

Why do we need these whitespace changes?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 155 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-N9IZ4HcQWbAF9gb0:-Mo-N9IZ4HcQWbAF9gb1:buaq3t8) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L155)):*
> ```
> // cbt::RowRange::InfiniteRange(),
> ```
Please remove this comment
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_set.cc, line 31 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-NW-ZEMBEba7hv0AQ:-Mo-NW-ZEMBEba7hv0AR:bq5j2fb) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/kernels/bigtable/bigtable_row_set.cc#L31)):*
> ```cpp
> 
>  private:
>   StatusOr<BigtableRowSetResource*> CreateResource() override {
> ```

All these whitespace changes seem unrelated.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_set.cc, line 152 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-Z97w-XUMXtEYp0Uo:-Mo-Z97w-XUMXtEYp0Up:b-gvxqp6) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/kernels/bigtable/bigtable_row_set.cc#L152)):*
> ```cpp
>                         BigtableRowSetIntersectOp);
> 
> class BigtableRowSetIntersectTensorOp : public OpKernel {
> ```

As i mentioned somewhere below - I don't understand why this operator is necessary. The `BigtableSampleRowSets` already takes the user-provided row-set into account.
___
*[tensorflow_io/core/kernels/gsmemcachedfs/memcached_file_block_cache.cc, line 762 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-L3GNBFLkYQfaytc_:-Mo-L3GNBFLkYQfaytca:bwddp6h) ([raw file](https://github.com/unoperate/tensorflow_io/blob/e38878ca28583b30586a2167c4d130811618678d/tensorflow_io/core/kernels/gsmemcachedfs/memcached_file_block_cache.cc#L762)):*
> ```cpp
>     auto page = absl::make_unique<std::vector<char>>();
>     page->assign(data->begin(), data->end());
>     cache_buffer_map_.emplace(memc_key, page.release());
> ```

That seems accidental.
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 97 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-aakC0HA0HAhFiEfh:-Mo-aakC0HA0HAhFiEfi:btbzvpg) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/ops/bigtable_ops.cc#L97)):*
> ```
> REGISTER_OP("BigtableRowSetIntersectTensor")
> ```
I'm sorry, but I don't understand why this is needed. BigtableSampleRowSets already intersects the the tablet list with the row set passed by the user, so why do it again?
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 106 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-b6rc-Uh1miMSAt94:-Mo-b6rd9-m_SbuBwKEt:b-hc2k4p) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/ops/bigtable_ops.cc#L106)):*
> ```
> BigtableSampleRowSets
> ```
I think this name can be misleading. `SampleRowKeys` was accurate - these was a (hopefully evenly) spread out sample of the row keys. This is a (hopefully even) row range split (i.e. covering all the given row set - not a sample).

How about `BigtableSplitRangeEvenly` or something along those lines?
___
*[tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py, line 47 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-VI7i2oXjNndYG2OR:-Mo-VI7i2oXjNndYG2OS:bimf5ay) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py#L47)):*
> ```Python
>         self,
>         columns: List[str],
>         num_parallel_calls=1,
> ```

I think this default is not a fortunate one.

`multiprocessing.cpu_count()` is a guess like any other but at least it's likely to be significantly different from `read_rows`.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/4)* status: 0 of 18 files reviewed, 8 unresolved discussions (waiting on @dopiera)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 34 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-MtOe724gaO9OO9-e:-Mo3E4Nf9v5QtWf4qpdK:b-x8s39n) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L34)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Why do we need these whitespace changes?
</blockquote></details>

I forgot to run the linter on that part before, that's why it's making this change. Good news is at least that it's not going to happen again.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 155 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-N9IZ4HcQWbAF9gb0:-Mo3Ifd85Fp9fMmRzeV_:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L155)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> // cbt::RowRange::InfiniteRange(),
> ```
Please remove this comment
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_set.cc, line 31 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-NW-ZEMBEba7hv0AQ:-Mo3IuQP1Qy-vg7dsCVl:b97q7d8) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/kernels/bigtable/bigtable_row_set.cc#L31)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

All these whitespace changes seem unrelated.
</blockquote></details>

As I said I run the linter.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_set.cc, line 152 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-Z97w-XUMXtEYp0Uo:-Mo8foc7CcVQZEIzSUGa:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/kernels/bigtable/bigtable_row_set.cc#L152)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

As i mentioned somewhere below - I don't understand why this operator is necessary. The `BigtableSampleRowSets` already takes the user-provided row-set into account.
</blockquote></details>

Done.
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 97 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-aakC0HA0HAhFiEfh:-Mo8frw8ELwh_0pf2sPN:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/ops/bigtable_ops.cc#L97)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> REGISTER_OP("BigtableRowSetIntersectTensor")
> ```
I'm sorry, but I don't understand why this is needed. BigtableSampleRowSets already intersects the the tablet list with the row set passed by the user, so why do it again?
</blockquote></details>

Done.
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 106 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-b6rc-Uh1miMSAt94:-Mo8g0Jf-h1VWyij5yaB:b-i1r68w) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/ops/bigtable_ops.cc#L106)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> BigtableSampleRowSets
> ```
I think this name can be misleading. `SampleRowKeys` was accurate - these was a (hopefully evenly) spread out sample of the row keys. This is a (hopefully even) row range split (i.e. covering all the given row set - not a sample).

How about `BigtableSplitRangeEvenly` or something along those lines?
</blockquote></details>

How about `BigtableSplitRowSetEvenly`? since the thing we are splitting is a user-specified row set.
___
*[tensorflow_io/core/kernels/gsmemcachedfs/memcached_file_block_cache.cc, line 762 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-L3GNBFLkYQfaytc_:-Mo8_LJF0HNu7_qkWc2s:b3l32jg) ([raw file](https://github.com/unoperate/tensorflow_io/blob/e38878ca28583b30586a2167c4d130811618678d/tensorflow_io/core/kernels/gsmemcachedfs/memcached_file_block_cache.cc#L762)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

That seems accidental.
</blockquote></details>

Whoops, good catch!
___
*[tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py, line 47 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-VI7i2oXjNndYG2OR:-Mo8h8PvBYdx2evOcm6G:b-75uf44) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py#L47)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think this default is not a fortunate one.

`multiprocessing.cpu_count()` is a guess like any other but at least it's likely to be significantly different from `read_rows`.
</blockquote></details>

Alrighty. :chipmunk: 
It turns out that TF already has a const value `tf.data.AUTOTUNE` which is set to the suggested number of threads, so I used that.

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/4)* status: 0 of 18 files reviewed, 13 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 272 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA0vcV6ediJ1RqW6VR:-MoA0vcV6ediJ1RqW6VS:b28e8v2) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L272)):*
> ```cpp
>   mutex mu_;
>   const std::vector<std::pair<std::string, std::string>> columns_;
>   cbt::Table table_;
> ```

Why is table_ not `GUARDED_BY(mu_)`?

Also, why do you even need it? I haven't noticed any uses?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 316 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA-52A3sVZfGVMk_5_:-MoA-52A3sVZfGVMk_5a:bqbvwq8) ([raw file](https://github.com/unoperate/tensorflow_io/blob/e38878ca28583b30586a2167c4d130811618678d/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L316)):*
> ```cpp
>  private:
>   BigtableClientResource& client_resource_;
>   const core::ScopedUnref client_resource_unref_;
> ```

Why don't we need to unref the client resource anymore?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 332 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA-8G6CWAsKydfVMJ0:-MoA-8G6CWAsKydfVMJ1:b-3085c0) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L332)):*
> ```cpp
>  private:
>   BigtableClientResource& client_resource_;
>   io::BigtableRowSetResource& row_set_resource_;
> ```

Why do we need to hold the whole resource? If we do, I think we need to `ref` and `unref` it - why not keep its contents instead?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 356 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA1pii8i_IkPjUSo6g:-MoA1pii8i_IkPjUSo6h:b3qq77u) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L356)):*
> ```cpp
>     OP_REQUIRES_OK(ctx,
>                    GetResourceFromContext(ctx, "row_set", &row_set_resource));
>     core::ScopedUnref row_set_resource_unref_(row_set_resource);
> ```

Please remove the trailing underscore from the local variable. Also, as mentioned earlier, I think it's easier if you pass the `RowSet` here instead of the `RowSetReasource`.

Slightly unrelated, but that might also be the case for the `client_resource` (i.e. you could simply pass the `DataClient`).
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 405 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA4kbV7UHljYOJidKz:-MoA4kbV7UHljYOJidL-:blvh1cm) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L405)):*
> ```
> num_parallel_calls
> ```
That is not a self-explanatory name in this context. How about `num_shards` or `num_splits`?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 461 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA6gSm0JN5Fy4qR2xY:-MoA6gSm0JN5Fy4qR2xZ:bzbqopw) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L461)):*
> ```
> (size_t)
> ```
Please don't use C-style casts. Use `static_cast`, `dynamic_cast`, `const_cast` or `reinterpret_cast` depending on the context. Here, it will probably be easiest to explicitly instantiate the `std::min` template, i.e. `std::min<std::size_t>(somthing)`.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 464 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA73VBDjcbKgpliRUZ:-MoA73VBDjcbKgpliRU_:b5eg2ce) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L464)):*
> ```
> (long)
> ```
`static_cast`, please.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 495 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA51O_4fp8SiDGkXE-:-MoA51O_4fp8SiDGkXE0:ba8isnq) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L495)):*
> ```cpp
>  private:
>   mutable mutex mu_;
>   std::string table_id_;
> ```

Please add the concurrency annotations.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_set.cc, line 152 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-Z97w-XUMXtEYp0Uo:-MoA7FqlClYkaK_KGNbH:b-bwaexq) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/kernels/bigtable/bigtable_row_set.cc#L152)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's still here.
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 97 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-aakC0HA0HAhFiEfh:-MoA7M9r8z6mEXOOBSPJ:b-bwaexq) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/ops/bigtable_ops.cc#L97)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's still here.
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 106 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-b6rc-Uh1miMSAt94:-MoA7Q1f4KEHVzoJoJLS:b9flql9) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/ops/bigtable_ops.cc#L106)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

How about `BigtableSplitRowSetEvenly`? since the thing we are splitting is a user-specified row set.
</blockquote></details>

Even better.
___
*[tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py, line 47 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-VI7i2oXjNndYG2OR:-MoA7Rts2pktvm7C7-1C:b9flql9) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py#L47)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

Alrighty. :chipmunk: 
It turns out that TF already has a const value `tf.data.AUTOTUNE` which is set to the suggested number of threads, so I used that.
</blockquote></details>

Even better.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/4)* status: 0 of 18 files reviewed, 13 unresolved discussions (waiting on @dopiera)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 272 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA0vcV6ediJ1RqW6VR:-MorsUn47HQ7fc9McvOw:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L272)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Why is table_ not `GUARDED_BY(mu_)`?

Also, why do you even need it? I haven't noticed any uses?
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 316 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA-52A3sVZfGVMk_5_:-MosMN3KDcCz8KZW4Mpl:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/e38878ca28583b30586a2167c4d130811618678d/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L316)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Why don't we need to unref the client resource anymore?
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 332 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA-8G6CWAsKydfVMJ0:-MosMLAZ4PsHgonv80dt:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L332)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Why do we need to hold the whole resource? If we do, I think we need to `ref` and `unref` it - why not keep its contents instead?
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 356 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA1pii8i_IkPjUSo6g:-MosMKh_07EgUygHkXeD:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L356)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Please remove the trailing underscore from the local variable. Also, as mentioned earlier, I think it's easier if you pass the `RowSet` here instead of the `RowSetReasource`.

Slightly unrelated, but that might also be the case for the `client_resource` (i.e. you could simply pass the `DataClient`).
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 405 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA4kbV7UHljYOJidKz:-MosMni6326fN7hB77S1:b-u2yzo3) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L405)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> num_parallel_calls
> ```
That is not a self-explanatory name in this context. How about `num_shards` or `num_splits`?
</blockquote></details>

Done. I think that `num_splits` might be best.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 461 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA6gSm0JN5Fy4qR2xY:-MosNDQoEQcVWEcv4ofP:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L461)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> (size_t)
> ```
Please don't use C-style casts. Use `static_cast`, `dynamic_cast`, `const_cast` or `reinterpret_cast` depending on the context. Here, it will probably be easiest to explicitly instantiate the `std::min` template, i.e. `std::min<std::size_t>(somthing)`.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 464 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA73VBDjcbKgpliRUZ:-MosOkh0DYYawiQ03MTE:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L464)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> (long)
> ```
`static_cast`, please.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 495 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA51O_4fp8SiDGkXE-:-MosOwqg1CRfgZs5rdsm:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L495)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Please add the concurrency annotations.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_set.cc, line 152 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-Z97w-XUMXtEYp0Uo:-MosP61U9iEm2Pkl-SxJ:b-ik7jaw) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/kernels/bigtable/bigtable_row_set.cc#L152)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

It's still here.
</blockquote></details>

No it's not. This one is just the good old `RowSet::Intersect` wrapper, so the user can create a `RowSet` and Intersect it with a `RowRange` or something. The other one was called `RowSetIntersectTensor` and got removed.
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 97 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-aakC0HA0HAhFiEfh:-MosPiJi7B9onJi18MQF:bswv8b6) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/ops/bigtable_ops.cc#L97)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

It's still here.
</blockquote></details>

It's not :smile: .  `BigtableRowSetIntersectTensor` doesn't exist. Are you sure you're looking at full diff?
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 106 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-b6rc-Uh1miMSAt94:-MosPwA52geB2eUSWQ4q:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/ops/bigtable_ops.cc#L106)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Even better.
</blockquote></details>

Done.
___
*[tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py, line 47 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-VI7i2oXjNndYG2OR:-MosQ1TK03ggcXNvD_d7:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py#L47)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Even better.
</blockquote></details>

Done.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/4)* status: 0 of 18 files reviewed, 13 unresolved discussions (waiting on @dopiera)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 332 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA-8G6CWAsKydfVMJ0:-MosQyIR2mkwBEa27PUO:bdk24ph) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L332)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm storing the data_client and row_set by value now, as you suggested.

**Review by dopiera — CHANGES_REQUESTED** [review]
Almost there.

> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-:-Mp2wwqa4bvEBj_ZFEBs:b-debr7t)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 272 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-MoA0vcV6ediJ1RqW6VR:-Mp2uzf995jjKRqh_cH3:b-w3wq48) ([raw file](https://github.com/unoperate/tensorflow_io/blob/c5a8fae921571b904bdda526a8732a0fe408bed4/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L272)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But you only commented it out rather than removing.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_set.cc, line 152 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-Z97w-XUMXtEYp0Uo:-Mp2wVGl4qchcT8xjWoH:b83n6xf) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/kernels/bigtable/bigtable_row_set.cc#L152)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

No it's not. This one is just the good old `RowSet::Intersect` wrapper, so the user can create a `RowSet` and Intersect it with a `RowRange` or something. The other one was called `RowSetIntersectTensor` and got removed.
</blockquote></details>

Oops, you're right
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 97 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/4#-Mo-aakC0HA0HAhFiEfh:-Mp2wbYMCeWnaRMVzPsX:b4b88wr) ([raw file](https://github.com/unoperate/tensorflow_io/blob/963d3b35e24138fb0719811e097c02cff5c69887/tensorflow_io/core/ops/bigtable_ops.cc#L97)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

It's not :smile: .  `BigtableRowSetIntersectTensor` doesn't exist. Are you sure you're looking at full diff?
</blockquote></details>

Weird, but you're right - it looks good now.

**Review by dopiera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/4)* status: 0 of 18 files reviewed, all discussions resolved (waiting on @dopiera)

**Pull request merged**
