### PR TITLE
feat: support for other data types

### PR DESCRIPTION
**Pull request by kboroszko**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/5)

### CODE REVIEW

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/5)* status: 0 of 5 files reviewed, 14 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 34 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mnzx7Fv6rfXqQvJcxKs:-Mnzx7Fv6rfXqQvJcxKt:bc00lod) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L34)):*
> ```cpp
> 
> tensorflow::error::Code GoogleCloudErrorCodeToTfErrorCode(
>     ::google::cloud::StatusCode code) {
> ```

Why these formatting changes?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 281 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-MnzxcLrCgf8GbGdVvuY:-MnzxcLrCgf8GbGdVvuZ:b-c36sqq) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L281)):*
> ```cpp
>         client_resource_(*client_resource),
>         client_resource_unref_(client_resource),
>         row_set_resource_(*row_set_resource),
> ```

What do we need it for? I don't see any uses. Besides, if we're storing this, we should increase the ref counter, no?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 351 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-HYTv3rLOKomLeUsw:-Mo-HYTv3rLOKomLeUsx:bo33993) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L351)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     io::BigtableRowSetResource* row_set_resource;
>     OP_REQUIRES_OK(ctx,
>                    GetResourceFromContext(ctx, "row_set", &row_set_resource));
>     core::ScopedUnref row_set_resource_unref_(row_set_resource);
> 
> ```
</details>

This seems unrelated to the data types, no?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 1 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-H2wz2jyVOdFN3fnL:-Mo-H2x-ARQQqnphwPD4:b-bzdnz1) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L1)):*
> ```
> /* Copyright 2021 The TensorFlow Authors. All Rights Reserved.
> 
> ```
Please add a comment explaining that we're using XDR because this seems consistent with what HBase is using.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 16 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-09-w4-y5vfnTKQa6:-Mo-09-w4-y5vfnTKQa7:b-mjey8x) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L16)):*
> ```objc
> ==============================================================================*/
> 
> #ifndef BIGTABLE_LIB_H
> ```

That's a very generic file name compared with its very specific contents.

How about we call it along the lines of `serialization.h`?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 20 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-7UnL7N_N3WPp7-uy:-Mo-7UnL7N_N3WPp7-uz:b-gexwr1) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L20)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> #include "absl/memory/memory.h"
> #include "google/cloud/bigtable/table.h"
> #include "google/cloud/bigtable/table_admin.h"
> #include "rpc/rpc.h" /* xdr is a sub-library of rpc */
> #include "tensorflow/core/framework/common_shape_fns.h"
> #include "tensorflow/core/framework/dataset.h"
> #include "tensorflow/core/framework/op.h"
> #include "tensorflow/core/framework/op_kernel.h"
> #include "tensorflow/core/framework/resource_mgr.h"
> #include "tensorflow/core/framework/resource_op_kernel.h"
> #include "tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h"
> #include "tensorflow_io/core/kernels/bigtable/bigtable_row_range.h"
> ```
</details>

Vast majority of these headers doesn't seem needed - please remove the unnecessary.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 22 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo--IIz4t22iF8suLwz:-Mo--IIz4t22iF8suLx-:b-djodck) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L22)):*
> ```
> rpc
> ```
then maybe `rpc/xdr.h`?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 33 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-7L4D65ZfioDee345:-Mo-7L4D65ZfioDee346:be2ypuo) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L33)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> using ::tensorflow::DT_STRING;
> using ::tensorflow::PartialTensorShape;
> using ::tensorflow::Status;
> 
> namespace cbt = ::google::cloud::bigtable;
> ```
</details>

Please don't do this in header files.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 40 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-12BWDRNBiKgSoyOQ:-Mo-12BWDRNBiKgSoyOR:b-lcbojb) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L40)):*
> ```objc
> namespace tensorflow {
> namespace data {
> namespace {
> ```

Anonymous namespaces in headers is are fishy at best. Every compilation unit including this file will have their own copy of these functions. I don't think it makes any sense. 
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 42 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-27VsBMVLqUqnGhIg:-Mo-27VsBMVLqUqnGhIh:bobjwp4) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L42)):*
> ```objc
> namespace {
> 
> std::string FloatToBytes(float v) {
> ```

When you define functions in a header file, you should make them inline - otherwise every compilation unit will compile them. 
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 47 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-FjTe0blkrIjd7dIt:-Mo-FjTe0blkrIjd7dIu:bo60j4x) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L47)):*
> ```objc
>   xdrmem_create(&xdrs, buffer, sizeof(v), XDR_ENCODE);
>   if (!xdr_float(&xdrs, &v)) {
>     throw std::runtime_error("Error writing float to byte array.");
> ```

I'm afraid we should change the error reporting to `StatusOr` in TF. I guess the status should be "invalid argument".
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 147 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-3_a200VMVwZGuwE4:-Mo-3_a200VMVwZGuwE5:bh5hci4) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L147)):*
If an non-templated function is defined in a header file it should be inline.

BUT, Google's style guide says:
> A decent rule of thumb is to not inline a function if it is more than 10 lines long.

I think it's fine if per-datatype functions are inline, but this one shouldn't.

Long story short - please move all these functions to a `.cc` file and make the others inline but not this one.

I was about to also say that we should also avoid calling this switch for every cell but given that we're doing a lookup in a hashmap anyway, I think this extra cost is negligible and we can leave the code structure as is.
___
*[tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py, line 40 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-FOALD9eH7d8CZVkw:-Mo-FOALD9eH7d8CZVkx:b49eu81) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py#L40)):*
> ```Python
>         )
> 
>     def parallel_read_rows(
> ```

This seems to belong to a different PR.
___
*[tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py, line 82 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-HMDE1I3Nj02sbstT:-Mo-HMDE1I3Nj02sbstU:b9fijgd) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py#L82)):*
> ```
> row_set: row_set.RowSet,
> ```
The `row_set` part seems to be from a different PR.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/5)* status: 0 of 5 files reviewed, 14 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 34 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mnzx7Fv6rfXqQvJcxKs:-Mot6Fh-7fE226PVhY3l:b-nyoqmj) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L34)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Why these formatting changes?
</blockquote></details>

linter
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 281 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-MnzxcLrCgf8GbGdVvuY:-Mot9WEw2YZzMm2RYIaK:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L281)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

What do we need it for? I don't see any uses. Besides, if we're storing this, we should increase the ref counter, no?
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 351 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-HYTv3rLOKomLeUsw:-Mot9eoE8saZiqWjSmAp:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L351)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
>     io::BigtableRowSetResource* row_set_resource;
>     OP_REQUIRES_OK(ctx,
>                    GetResourceFromContext(ctx, "row_set", &row_set_resource));
>     core::ScopedUnref row_set_resource_unref_(row_set_resource);
> 
> ```
This seems unrelated to the data types, no?
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 16 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-09-w4-y5vfnTKQa6:-MotRdHb8W4XrwRpdij7:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L16)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

That's a very generic file name compared with its very specific contents.

How about we call it along the lines of `serialization.h`?
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 20 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-7UnL7N_N3WPp7-uy:-MotNgyw7Zln-TNojZVc:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L20)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> #include "absl/memory/memory.h"
> #include "google/cloud/bigtable/table.h"
> #include "google/cloud/bigtable/table_admin.h"
> #include "rpc/rpc.h" /* xdr is a sub-library of rpc */
> #include "tensorflow/core/framework/common_shape_fns.h"
> #include "tensorflow/core/framework/dataset.h"
> #include "tensorflow/core/framework/op.h"
> #include "tensorflow/core/framework/op_kernel.h"
> #include "tensorflow/core/framework/resource_mgr.h"
> #include "tensorflow/core/framework/resource_op_kernel.h"
> #include "tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h"
> #include "tensorflow_io/core/kernels/bigtable/bigtable_row_range.h"
> ```
Vast majority of these headers doesn't seem needed - please remove the unnecessary.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 22 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo--IIz4t22iF8suLwz:-MotNhUF1bO6FIrUQH6S:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L22)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> rpc
> ```
then maybe `rpc/xdr.h`?
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 33 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-7L4D65ZfioDee345:-MotNjTv-I_eqI6SKLjj:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L33)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> using ::tensorflow::DT_STRING;
> using ::tensorflow::PartialTensorShape;
> using ::tensorflow::Status;
> 
> namespace cbt = ::google::cloud::bigtable;
> ```
Please don't do this in header files.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 40 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-12BWDRNBiKgSoyOQ:-MotNkPG5Y4ik1rHfiE8:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L40)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Anonymous namespaces in headers is are fishy at best. Every compilation unit including this file will have their own copy of these functions. I don't think it makes any sense. 
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 42 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-27VsBMVLqUqnGhIg:-MotObqe-la3soCGh2DD:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L42)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

When you define functions in a header file, you should make them inline - otherwise every compilation unit will compile them. 
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 47 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-FjTe0blkrIjd7dIt:-MotOi3g5oY54E2SWccN:bdcv6l8) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L47)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I'm afraid we should change the error reporting to `StatusOr` in TF. I guess the status should be "invalid argument".
</blockquote></details>

Good point.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 147 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-3_a200VMVwZGuwE4:-MotRR8-AEqBAJFLhF2N:bmrw47n) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L147)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

If an non-templated function is defined in a header file it should be inline.

BUT, Google's style guide says:
> A decent rule of thumb is to not inline a function if it is more than 10 lines long.

I think it's fine if per-datatype functions are inline, but this one shouldn't.

Long story short - please move all these functions to a `.cc` file and make the others inline but not this one.

I was about to also say that we should also avoid calling this switch for every cell but given that we're doing a lookup in a hashmap anyway, I think this extra cost is negligible and we can leave the code structure as is.
</blockquote></details>

Oh goodie.
___
*[tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py, line 40 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-FOALD9eH7d8CZVkw:-Mo34lQ0DMX3vOJFRAFb:b-8e3bon) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py#L40)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This seems to belong to a different PR.
</blockquote></details>

damn it!

**Review by dopiera — COMMENTED** [review]
I think you responded to the comments but forgot to push the changes (or at least I can't see them in Reviewable).

> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-:-Mp2xMl65Yg3RqoSXlLt:bvla2x4)* status: 0 of 5 files reviewed, 13 unresolved discussions (waiting on @dopiera and @kboroszko)

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/5)* status: 0 of 9 files reviewed, 13 unresolved discussions (waiting on @dopiera)

___
*[tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py, line 82 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-HMDE1I3Nj02sbstT:-Mp6OeZI9kTLi94VksqR:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py#L82)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> row_set: row_set.RowSet,
> ```
The `row_set` part seems to be from a different PR.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 1 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-H2wz2jyVOdFN3fnL:-Mp6Di5TAhpWC0dxJrXw:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L1)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> /* Copyright 2021 The TensorFlow Authors. All Rights Reserved.
> 
> ```
Please add a comment explaining that we're using XDR because this seems consistent with what HBase is using.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_lib.h, line 147 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mo-3_a200VMVwZGuwE4:-Mp6UBWf0a90Bz9fNzEP:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/67a412ee0a99d5741f401e71f1183b36bbbca737/tensorflow_io/core/kernels/bigtable/bigtable_lib.h#L147)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

Oh goodie.
</blockquote></details>

Done.

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/5)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/serialization.h, line 18 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mp7HY-m-QUX4emfJuFd:-Mp7HY-m-QUX4emfJuFe:b-dfuedm) ([raw file](https://github.com/unoperate/tensorflow_io/blob/b2a55e8bb55040d552d3e40375c56d2815aab150/tensorflow_io/core/kernels/bigtable/serialization.h#L18)):*
> ```
> Byte representation of basic types may depend on language and architecture, thus
> we need something that is invariant and consistent with HBase. XDR library seems
> to satisfy those constraints.
> ```
Sorry for being obnoxious here, but could you please move this comment to a separate comment? I almost missed it, thinking it's a part of the copyright header.

Also, could you please include a sentence along these lines:
> Bigtable only stores byte buffers as values - except for `int64` the server side does not have any notion of types. Tensorflow, needs to store shorter integers, floats, doubles, so we needed to decide on how. We chose to follow what HBase does, since there is a path for migrating from HBase to Bigtable. XDR seems to match what HBase does.
___
*[tensorflow_io/core/kernels/bigtable/serialization.h, line 25 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mp7U5DW4ce5_vX20L69:-Mp7U5DX2omp_TkQEiNR:b-fv97u6) ([raw file](https://github.com/unoperate/tensorflow_io/blob/b2a55e8bb55040d552d3e40375c56d2815aab150/tensorflow_io/core/kernels/bigtable/serialization.h#L25)):*
> ```objc
> 
> #include "google/cloud/bigtable/table.h"
> #include "rpc/xdr.h" /* xdr is a sub-library of rpc */
> ```

Now this comment seems stale. Also, I don't think you need this `#include` in the header, please move it to the `.cc` file. I think this applies to most of the `#include`s in this file, actually.
___
*[tensorflow_io/core/kernels/bigtable/serialization.cc, line 1 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mp7UltjEOZNGNq22fXq:-Mp7UltjEOZNGNq22fXr:b87fax4) ([raw file](https://github.com/unoperate/tensorflow_io/blob/b2a55e8bb55040d552d3e40375c56d2815aab150/tensorflow_io/core/kernels/bigtable/serialization.cc#L1)):*
> ```cpp
> /* Copyright 2021 The TensorFlow Authors. All Rights Reserved.
> ```

I noticed it only now - there are functions for converting types to bytes - we're not using them here. Please remove them.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/5)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @dopiera)

___
*[tensorflow_io/core/kernels/bigtable/serialization.h, line 18 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mp7HY-m-QUX4emfJuFd:-MpBNVAY5gDpzGOqoZik:bsis56u) ([raw file](https://github.com/unoperate/tensorflow_io/blob/b2a55e8bb55040d552d3e40375c56d2815aab150/tensorflow_io/core/kernels/bigtable/serialization.h#L18)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> Byte representation of basic types may depend on language and architecture, thus
> we need something that is invariant and consistent with HBase. XDR library seems
> to satisfy those constraints.
> ```
Sorry for being obnoxious here, but could you please move this comment to a separate comment? I almost missed it, thinking it's a part of the copyright header.

Also, could you please include a sentence along these lines:
> Bigtable only stores byte buffers as values - except for `int64` the server side does not have any notion of types. Tensorflow, needs to store shorter integers, floats, doubles, so we needed to decide on how. We chose to follow what HBase does, since there is a path for migrating from HBase to Bigtable. XDR seems to match what HBase does.
</blockquote></details>

Now it's impossible to miss. :+1: 
___
*[tensorflow_io/core/kernels/bigtable/serialization.h, line 25 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mp7U5DW4ce5_vX20L69:-MpBLXaM5i_6F6jZOJFr:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/b2a55e8bb55040d552d3e40375c56d2815aab150/tensorflow_io/core/kernels/bigtable/serialization.h#L25)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Now this comment seems stale. Also, I don't think you need this `#include` in the header, please move it to the `.cc` file. I think this applies to most of the `#include`s in this file, actually.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/serialization.cc, line 1 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/5#-Mp7UltjEOZNGNq22fXq:-MpBGg0CCSLgB2h0yYeO:b-qm17cl) ([raw file](https://github.com/unoperate/tensorflow_io/blob/b2a55e8bb55040d552d3e40375c56d2815aab150/tensorflow_io/core/kernels/bigtable/serialization.cc#L1)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I noticed it only now - there are functions for converting types to bytes - we're not using them here. Please remove them.
</blockquote></details>

Sure. I added them expecting the code in for writing to BT in the next PRs. But, since we're not doing that, I guess it's obsolete.

**Review by dopiera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/5)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @dopiera)

**Pull request merged**
