### PR TITLE
fix: building on windows

### PR DESCRIPTION
**Pull request by kboroszko**
This PR fixes building on Windows by: 

- adding serialization methods on windows, because we can't use xdr.
- changing OPTIONAL to OPIONAL in field_behavior.proto. For more info look [here](https://github.com/protocolbuffers/protobuf/issues/7076).

---
This change is [Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/12)

### CODE REVIEW

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/12)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[bld.sh, line 1 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/12#-MpgV-ojD87pfoFW1FHY:-MpgV-okA36qo7m_wGx3:b-lyb4fg) ([raw file](https://github.com/unoperate/tensorflow_io/blob/26203572a95771da00713628d9992c27c3c0565a/bld.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

I'm guessing this file got here by accident, right?
___
*[WORKSPACE, line 112 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/12#-MpgVBvn5nw_K5LoYCYh:-MpgVBvn5nw_K5LoYCYi:b-1rzlkg) ([raw file](https://github.com/unoperate/tensorflow_io/blob/26203572a95771da00713628d9992c27c3c0565a/WORKSPACE#L112)):*
> ```
> https://github.com/protocolbuffers/protobuf/issues/7076
> ```
I think we need more explanation that that.

How about this:
Because of a bug in protocol buffers (https://github.com/protocolbuffers/protobuf/issues/7076), new versions of this project fail to compile on Windows. The problem hinges on `OPTIONAL` being defined as an empty string under Windows. This makes the preprocessor remove every mention of `OPTIONAL` from the code, which causes compilation failures. This temporary workaround renames the name of the protobuf value `OPTIONAL` to `OPIONAL`. This should be safe as it does not affect the generated protobufs.
___
*[WORKSPACE, line 118 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/12#-MpgWjGsBTPPJX2QSvSp:-MpgWjGsBTPPJX2QSvSq:bzdqdpq) ([raw file](https://github.com/unoperate/tensorflow_io/blob/26203572a95771da00713628d9992c27c3c0565a/WORKSPACE#L118)):*
> ```
> -i.bak
> ```
what do we need those `*.bak`s for?
___
*[tensorflow_io/core/kernels/bigtable/serialization.h, line 28 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/12#-MpgWtYr1VWVOi89y6AY:-MpgWtYr1VWVOi89y6AZ:b-vuw2vj) ([raw file](https://github.com/unoperate/tensorflow_io/blob/26203572a95771da00713628d9992c27c3c0565a/tensorflow_io/core/kernels/bigtable/serialization.h#L28)):*
> ```
> values as byte buffers
> ```
I think it should be "byte buffers as values".
___
*[tensorflow_io/core/kernels/bigtable/serialization.h, line 32 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/12#-MpgXOSs8FBsUMmUTkAL:-MpgXOSs8FBsUMmUTkAM:batfov8) ([raw file](https://github.com/unoperate/tensorflow_io/blob/26203572a95771da00713628d9992c27c3c0565a/tensorflow_io/core/kernels/bigtable/serialization.h#L32)):*
> ```
>  XDR seems to match what HBase does.
> ```
I think we need to elaborate on why we need two implementations.

I think we should say the following:
> HBase stores integers as big-endian and floats as IEEE754 (also big-endian). Given that integer endianness does not always match float endianness, and the fact that there are architectures where it is neither little nor big (BE-32), implementing this properly is non-trivial. Ideally, we would use a library to do that. XDR matches what HBase does, but it is not easily available on Windows, so we decided to go with a hybrid approach. On Windows we assume that integer endianness matches float endianness and implement the deserialization ourselves and everywhere else we use XDR. For that reason we provide two implementations

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/12)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @dopiera)

___
*[WORKSPACE, line 112 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/12#-MpgVBvn5nw_K5LoYCYh:-Mpgl2Nv8oXY5ZRLF4-g:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/26203572a95771da00713628d9992c27c3c0565a/WORKSPACE#L112)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> https://github.com/protocolbuffers/protobuf/issues/7076
> ```
I think we need more explanation that that.

How about this:
Because of a bug in protocol buffers (https://github.com/protocolbuffers/protobuf/issues/7076), new versions of this project fail to compile on Windows. The problem hinges on `OPTIONAL` being defined as an empty string under Windows. This makes the preprocessor remove every mention of `OPTIONAL` from the code, which causes compilation failures. This temporary workaround renames the name of the protobuf value `OPTIONAL` to `OPIONAL`. This should be safe as it does not affect the generated protobufs.
</blockquote></details>

Done.
___
*[WORKSPACE, line 118 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/12#-MpgWjGsBTPPJX2QSvSp:-Mpgl5sc7TrFXmZQRpx-:bhg5gej) ([raw file](https://github.com/unoperate/tensorflow_io/blob/26203572a95771da00713628d9992c27c3c0565a/WORKSPACE#L118)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> -i.bak
> ```
what do we need those `*.bak`s for?
</blockquote></details>

Cargo cult.
___
*[tensorflow_io/core/kernels/bigtable/serialization.h, line 28 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/12#-MpgWtYr1VWVOi89y6AY:-MpglH3-3bx98Ze1FYM6:b-pryr6u) ([raw file](https://github.com/unoperate/tensorflow_io/blob/26203572a95771da00713628d9992c27c3c0565a/tensorflow_io/core/kernels/bigtable/serialization.h#L28)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> values as byte buffers
> ```
I think it should be "byte buffers as values".
</blockquote></details>

Actually, I don't get why. Each cell has a value, and this value is represented as bytes, no?
___
*[tensorflow_io/core/kernels/bigtable/serialization.h, line 32 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/12#-MpgXOSs8FBsUMmUTkAL:-MpglzoM-KVx_kZFPop1:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/26203572a95771da00713628d9992c27c3c0565a/tensorflow_io/core/kernels/bigtable/serialization.h#L32)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
>  XDR seems to match what HBase does.
> ```
I think we need to elaborate on why we need two implementations.

I think we should say the following:
> HBase stores integers as big-endian and floats as IEEE754 (also big-endian). Given that integer endianness does not always match float endianness, and the fact that there are architectures where it is neither little nor big (BE-32), implementing this properly is non-trivial. Ideally, we would use a library to do that. XDR matches what HBase does, but it is not easily available on Windows, so we decided to go with a hybrid approach. On Windows we assume that integer endianness matches float endianness and implement the deserialization ourselves and everywhere else we use XDR. For that reason we provide two implementations
</blockquote></details>

Done.
___
*[bld.sh, line 1 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/12#-MpgV-ojD87pfoFW1FHY:-MpgkfGyCwGfdt4aqZE7:b2nih0v) ([raw file](https://github.com/unoperate/tensorflow_io/blob/26203572a95771da00713628d9992c27c3c0565a/bld.sh#L1)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I'm guessing this file got here by accident, right?
</blockquote></details>

yup

**Review by dopiera — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/12)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @dopiera)

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/12)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @dopiera)

___
*[WORKSPACE, line 118 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/12#-MpgWjGsBTPPJX2QSvSp:-MppdIG-01tlwmaAuE7B:b-hcraw2) ([raw file](https://github.com/unoperate/tensorflow_io/blob/26203572a95771da00713628d9992c27c3c0565a/WORKSPACE#L118)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

Cargo cult.
</blockquote></details>

It turns out that we have this because without it the builiding on MacOS mysteriously fails. It's some problem with `sed` on OSX, but i didn't spend much time debugging it. All I know is it breaks, when I remove the `.bak`. Other sed's in this file use this option as well, I assume for the same reason. I don't think it's worth investigating.

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/12)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/serialization.h, line 28 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/12#-MpgWtYr1VWVOi89y6AY:-MpuxyKX0vujGmuh3_O1:bb57auk) ([raw file](https://github.com/unoperate/tensorflow_io/blob/26203572a95771da00713628d9992c27c3c0565a/tensorflow_io/core/kernels/bigtable/serialization.h#L28)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

Actually, I don't get why. Each cell has a value, and this value is represented as bytes, no?
</blockquote></details>

I think it's a tautology to say that data is stored as byte buffers - I don't think there's an alternative. After all, ints, floats, protobufs or images are all stored as byte buffers.

I think that when you say "byte buffers as values", you indicate that the only type of the value is a byte buffer, which is what we want to indicate here.

Either way, I think the reader will get what we mean, so fix it only if you like.
___
*[tests/test_bigtable/test_serialization.py, line 40 at r8](https://reviewable.io/reviews/unoperate/tensorflow_io/12#-MpuzWasDK166hths6Ye:-MpuzWasDK166hths6Yf:bdozdlv) ([raw file](https://github.com/unoperate/tensorflow_io/blob/0617cb16eea4939f7088e13e42866f294ae3a6c3/tests/test_bigtable/test_serialization.py#L40)):*
> ```Python
>         )
>     ):
>         test_case.assertEqual(values[i].numpy(), r.numpy()[0])
> ```

For floats and doubles you want `assertAlmostEqual`.

Also, why isn't this a method in `BigtableReadTest`?

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/12)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @dopiera)

___
*[tests/test_bigtable/test_serialization.py, line 40 at r8](https://reviewable.io/reviews/unoperate/tensorflow_io/12#-MpuzWasDK166hths6Ye:-MpwSZUv85148fSmePo1:bb6un1j) ([raw file](https://github.com/unoperate/tensorflow_io/blob/0617cb16eea4939f7088e13e42866f294ae3a6c3/tests/test_bigtable/test_serialization.py#L40)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

For floats and doubles you want `assertAlmostEqual`.

Also, why isn't this a method in `BigtableReadTest`?
</blockquote></details>

Done

**Review by dopiera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/12)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @dopiera)

**Pull request merged**
