### PR TITLE
feat: version filters

### PR DESCRIPTION
**Pull request by kboroszko**
This PR adds support for Bigtable version filters.

---
This change is [Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/6)

### CODE REVIEW

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/6)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 326 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/6#-Mp3-G699wuK3qNVF03B:-Mp3-G699wuK3qNVF03C:bd45h1m) ([raw file](https://github.com/unoperate/tensorflow_io/blob/4489e24444b39ba8cf79f1b732f5ba77ac899da7/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L326)):*
> ```
> filter_resource_
> ```
Given my limited understanding of the lifetimes of these object I think I'd be calmer if we kept the filter rather than the reference to the resource.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_version_filters.h, line 49 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/6#-Mp3-cqn6vvMM4FVPNX9:-Mp3-cqn6vvMM4FVPNXA:b6m9h2h) ([raw file](https://github.com/unoperate/tensorflow_io/blob/4489e24444b39ba8cf79f1b732f5ba77ac899da7/tensorflow_io/core/kernels/bigtable/bigtable_version_filters.h#L49)):*
> ```objc
>   }
> 
>   google::cloud::bigtable::Filter& filter() { return filter_; }
> ```

I think we should either return a cref or a value or call this member function in a way indicating that it returns a reference.

BTW, don't we need to care about concurrency here?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc, line 48 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/6#-Mp30FM-1HX2_9HFRpxp:-Mp30FM-1HX2_9HFRpxq:b-3ix6pw) ([raw file](https://github.com/unoperate/tensorflow_io/blob/4489e24444b39ba8cf79f1b732f5ba77ac899da7/tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc#L48)):*
> ```cpp
>       : AbstractBigtableResourceOp<BigtableFilterResource>(ctx) {
>     VLOG(1) << "BigtableTimestampRangeFilterOp ctor ";
>     OP_REQUIRES_OK(ctx, ctx->GetAttr("start", &start_));
> ```

Given that the type is essentially and int, why not make it a bit easier to the reader to figure out what it is and call it `start_ts_us` or at least `start_us` to indicate it's a timestamp expressed in microseconds?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc, line 57 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/6#-Mp30qRjD9xnHXqHoIOp:-Mp30qRjD9xnHXqHoIOq:bqagw04) ([raw file](https://github.com/unoperate/tensorflow_io/blob/4489e24444b39ba8cf79f1b732f5ba77ac899da7/tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc#L57)):*
> ```
>   mutable mutex mu_;
> ```
You don't need the `mutex`, do you?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc, line 59 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/6#-Mp30o849dt64pD-MEvh:-Mp30o849dt64pD-MEvi:bpnvaud) ([raw file](https://github.com/unoperate/tensorflow_io/blob/4489e24444b39ba8cf79f1b732f5ba77ac899da7/tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc#L59)):*
> ```
>   int64_t start_;
>   int64_t end_;
> ```
These can be `const`.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc, line 86 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/6#-Mp30wBuEcYH2XW18oxW:-Mp30wBvAiVErJYk-9tE:b-z65vj2) ([raw file](https://github.com/unoperate/tensorflow_io/blob/4489e24444b39ba8cf79f1b732f5ba77ac899da7/tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc#L86)):*
> ```
>   mutable mutex mu_;
> ```
I don't think you need the `mutex`

**Review by dopiera — COMMENTED** [review]
It looks good in general, I left a couple of nitpicks.

> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/6#-:-Mp31a5C0Ay49FgUAyrb:b-ydtuod)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @dopiera and @kboroszko)

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/6)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @dopiera)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 326 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/6#-Mp3-G699wuK3qNVF03B:-Mp6YbDlCRPJT4doi97i:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/4489e24444b39ba8cf79f1b732f5ba77ac899da7/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L326)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> filter_resource_
> ```
Given my limited understanding of the lifetimes of these object I think I'd be calmer if we kept the filter rather than the reference to the resource.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_version_filters.h, line 49 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/6#-Mp3-cqn6vvMM4FVPNX9:-Mp6XCBXARKZtQgujm2A:b-v1mxsl) ([raw file](https://github.com/unoperate/tensorflow_io/blob/4489e24444b39ba8cf79f1b732f5ba77ac899da7/tensorflow_io/core/kernels/bigtable/bigtable_version_filters.h#L49)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think we should either return a cref or a value or call this member function in a way indicating that it returns a reference.

BTW, don't we need to care about concurrency here?
</blockquote></details>

We set it in the constructor and never change it afterwards, so I'd say we don't since it's read-only. I changed it to const. How about that?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc, line 48 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/6#-Mp30FM-1HX2_9HFRpxp:-Mp6XwaCC3naRKvOcmyv:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/4489e24444b39ba8cf79f1b732f5ba77ac899da7/tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc#L48)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Given that the type is essentially and int, why not make it a bit easier to the reader to figure out what it is and call it `start_ts_us` or at least `start_us` to indicate it's a timestamp expressed in microseconds?
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc, line 57 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/6#-Mp30qRjD9xnHXqHoIOp:-Mp6XtqwE_DzSZd3Uibw:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/4489e24444b39ba8cf79f1b732f5ba77ac899da7/tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc#L57)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
>   mutable mutex mu_;
> ```
You don't need the `mutex`, do you?
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc, line 59 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/6#-Mp30o849dt64pD-MEvh:-Mp6XuFYCNfiuPEON8Jk:b4aemox) ([raw file](https://github.com/unoperate/tensorflow_io/blob/4489e24444b39ba8cf79f1b732f5ba77ac899da7/tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc#L59)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
>   int64_t start_;
>   int64_t end_;
> ```
These can be `const`.
</blockquote></details>

They can't because I must set them in the constructor with `ctx->GetAttr(name, ptr_to_value)`.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc, line 86 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/6#-Mp30wBuEcYH2XW18oxW:-Mp6Xv7q9Eh0J4XoeoK0:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/4489e24444b39ba8cf79f1b732f5ba77ac899da7/tensorflow_io/core/kernels/bigtable/bigtable_version_filters.cc#L86)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
>   mutable mutex mu_;
> ```
I don't think you need the `mutex`
</blockquote></details>

Done.

**Review by dopiera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/6)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @dopiera)

**Pull request merged**
