### PR TITLE
fix: linter fixes

### PR DESCRIPTION
**Pull request by kboroszko**
This PR fixes the files so they are consistent with CI linting and building and don't fail.
There is a few minor changes, mainly indents but also removing some `mutable` keywords that were not needed and adding a mutex in one place.

---
This change is [Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/8)

### CODE REVIEW

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/8)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @dopiera)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 136 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/8#-MpHePYzB1ZW3AOnxP2h:-MpHePYzB1ZW3AOnxP2i:b-rgqplx) ([raw file](https://github.com/unoperate/tensorflow_io/blob/1aa388078528783bf012dcf569abdfec32343563/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L136)):*
> ```cpp
> 
>  private:
>   mutex mu_;
> ```

anticipating the question, IDK why it used to compile but this mutex was not declared even though the `Compute` method declaration above is using it:

`void Compute(OpKernelContext* ctx) override TF_LOCKS_EXCLUDED(mu_) `
 ¯\_(ツ)_/¯

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/8)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @dopiera)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 136 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/8#-MpHePYzB1ZW3AOnxP2h:-MpHewnw6fTBV-IuF2LD:b-s46z4g) ([raw file](https://github.com/unoperate/tensorflow_io/blob/1aa388078528783bf012dcf569abdfec32343563/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L136)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

anticipating the question, IDK why it used to compile but this mutex was not declared even though the `Compute` method declaration above is using it:

`void Compute(OpKernelContext* ctx) override TF_LOCKS_EXCLUDED(mu_) `
 ¯\_(ツ)_/¯ 
</blockquote></details>

I only noticed it because the build for macOS was failing for this very reason.

**Review by dopiera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/8)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 136 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/8#-MpHePYzB1ZW3AOnxP2h:-MpICha09tdzhShxdv2m:b-iksvtg) ([raw file](https://github.com/unoperate/tensorflow_io/blob/1aa388078528783bf012dcf569abdfec32343563/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L136)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

I only noticed it because the build for macOS was failing for this very reason.
</blockquote></details>

But why would we keep a mutex that we don't use? Please remove the annotations instead.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/8)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @dopiera)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 136 at r1](https://reviewable.io/reviews/unoperate/tensorflow_io/8#-MpHePYzB1ZW3AOnxP2h:-MpKqFSJ444YPiP96RK4:bdiemev) ([raw file](https://github.com/unoperate/tensorflow_io/blob/1aa388078528783bf012dcf569abdfec32343563/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L136)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

But why would we keep a mutex that we don't use? Please remove the annotations instead.
</blockquote></details>

Right...

**Review by dopiera — APPROVED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/8)* status: all files reviewed, 1 unresolved discussion (waiting on @dopiera)

**Pull request merged**
